### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by hymced** [jordansaints/qlBitRate#3] opened 2015-03-15 21:46 UTC
Hi Jordan
I have used the pre-complied v1.1 release, and properly reseted QL with Terminal on my 10.9.4 install, but nothing changes !

![ccc](https://cloud.githubusercontent.com/assets/5414283/6658301/108413a0-cb65-11e4-8add-9c0f582998c9.png)

FYI I have found out about your plugin thanks to a guy answering a question of mine on stackoverflow 
http://stackoverflow.com/questions/25373373/quick-look-on-os-x-10-9-not-showing-title-artist-and-album-mp3-tags-anymore/29062952?iemail=1&noredirect=1#29062952

**Comment by hymced** [comment] 2015-03-18 20:40
I have just tried to build my own, not solving the problem...

**Comment by jordansaints** [comment] 2015-03-18 21:53
Hmm, I'm currently not having a problem on 10.9.5. Which folder are you placing the plugin in? If you are placing it in your user ~/Library/QuickLook/ folder, try your root level /Library/QuickLook/ folder instead.

If you're compiling it yourself, try changing the Base SDK under the Build Settings tab to your specific version of OS X. Have always kept it general in my release versions, so maybe your computer doesn't like that for some reason.

That's cool my plugin was recommended in a SO post ^_^ Thanks so much for linking that!

**Comment by hymced** [comment] 2015-03-18 21:59
Yes I am already using the root folder since the other one seems not to exist on my setup.

I'll try what you suggest with Xcode tomorrow and i will keep you posted !

In the mean time, could you also take a look at my initial prob on SO with QL ? The behavior I am describing on my post, is it familiar to you ?

Thx

CR

**Comment by jordansaints** [comment] 2015-03-23 17:30
You can create the folder at ~/Library/QuickLook (it's not uncommon that that folder doesn't exist on a fresh copy of OS X), although unfortunately, looking at your SO post, I don't think placing the plugin in your local Library folder will fix the issues you're having.

I haven't ever seen these issues before, although I've definitely had weirdness in my QuickLook before, usually over time the issues seems to resolve themselves.  What other QuickLook extensions do you have installed?  You could try removing them all, restarting your computer (at the very least completely log out and log back in), and see what happens.  Other potential fixes I can think of off the top of my head are to verify/repair your disk permissions using Disk Utility, clearing out your QuickLook config files (as suggested in the CNET article you linked), and/or you could also use something like Onyx to clear all of your caches and temp files.  If all else fails, it may just be an issue with your install of OS X, and you may need to do a fresh install to fix it completely (this isn't a hackintosh is it?).

**Comment by jordansaints** [comment] 2015-07-01 06:00
Closing this, as the issue is not related to qlBitRate.

**Closed by jordansaints** 2015-07-01 06:00 UTC
Labels: question

**Comment by hymced** [comment] 2015-07-01 15:39
The opposite hasn't been proved.
